//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suricato {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suricato.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!.
        /// </summary>
        internal static string Alerta {
            get {
                return ResourceManager.GetString("Alerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O seu dispositivo não possui uma camera ou ela está indisponível..
        /// </summary>
        internal static string CameraBloqueadaConteudo {
            get {
                return ResourceManager.GetString("CameraBloqueadaConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último registro de ponto não encontrado.
        /// </summary>
        internal static string ImagemRegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("ImagemRegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar.
        /// </summary>
        internal static string Iniciar {
            get {
                return ResourceManager.GetString("Iniciar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronto {0}! Foi fácil, né? Agora você pode utilizar o Suricato!.
        /// </summary>
        internal static string InicioConteudoFinal {
            get {
                return ResourceManager.GetString("InicioConteudoFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro informe os mesmos dados de acesso: sistema, e-mail e senha, que utiliza no portal Suricato e clique em PROSSEGUIR..
        /// </summary>
        internal static string InicioDadosConteudo {
            get {
                return ResourceManager.GetString("InicioDadosConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verificação de Dados.
        /// </summary>
        internal static string InicioDadosTitulo {
            get {
                return ResourceManager.GetString("InicioDadosTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse procedimento é realizado em poucos passos e apenas na primeira vez que é acessado. Insira abaixo a chave de registro Suricato..
        /// </summary>
        internal static string InicioInfo {
            get {
                return ResourceManager.GetString("InicioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Como esse é o seu primeiro acesso ao Suricato, vou lhe ajudar a configurar a sua conta..
        /// </summary>
        internal static string InicioIntroConteudo {
            get {
                return ResourceManager.GetString("InicioIntroConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá, bem-vindo ao Suricato!.
        /// </summary>
        internal static string InicioIntroTitulo {
            get {
                return ResourceManager.GetString("InicioIntroTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora confirme a senha que você cadastrou anteriormente.
        /// </summary>
        internal static string InicioSenhaConfirmaConteudo {
            get {
                return ResourceManager.GetString("InicioSenhaConfirmaConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas informadas não são iguais, veirifque.
        /// </summary>
        internal static string InicioSenhaConfirmaNaoBatePopUp {
            get {
                return ResourceManager.GetString("InicioSenhaConfirmaNaoBatePopUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal, {0}!.
        /// </summary>
        internal static string InicioSenhaConfirmaTitulo {
            get {
                return ResourceManager.GetString("InicioSenhaConfirmaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastramento de Senha.
        /// </summary>
        internal static string InicioSenhaConfirmaTituloPopup {
            get {
                return ResourceManager.GetString("InicioSenhaConfirmaTituloPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agora que sabemos quem você é, que tal facilitarmos o seu acesso ao aplicativo?.
        /// </summary>
        internal static string InicioSenhaConteudo {
            get {
                return ResourceManager.GetString("InicioSenhaConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, {0}!.
        /// </summary>
        internal static string InicioSenhaTitulo {
            get {
                return ResourceManager.GetString("InicioSenhaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleciona uma empresa.
        /// </summary>
        internal static string ListBoxCompanhia {
            get {
                return ResourceManager.GetString("ListBoxCompanhia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companhia.
        /// </summary>
        internal static string PalavraCompanhia {
            get {
                return ResourceManager.GetString("PalavraCompanhia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string PalavraEmail {
            get {
                return ResourceManager.GetString("PalavraEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrícula.
        /// </summary>
        internal static string PalavraMatricula {
            get {
                return ResourceManager.GetString("PalavraMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string PalavraSenha {
            get {
                return ResourceManager.GetString("PalavraSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escolha abaixo a sua empresa associada.
        /// </summary>
        internal static string PopUpEmpregadoresSeletor {
            get {
                return ResourceManager.GetString("PopUpEmpregadoresSeletor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresas.
        /// </summary>
        internal static string PopUpEmpregadoresTitulo {
            get {
                return ResourceManager.GetString("PopUpEmpregadoresTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, O QUE VOCÊ DESEJA FAZER?.
        /// </summary>
        internal static string PrincipalConteudo {
            get {
                return ResourceManager.GetString("PrincipalConteudo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espelho de Ponto.
        /// </summary>
        internal static string PrincipalEspelhoPonto {
            get {
                return ResourceManager.GetString("PrincipalEspelhoPonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Usuário.
        /// </summary>
        internal static string PrincipalNovoUsuario {
            get {
                return ResourceManager.GetString("PrincipalNovoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marcar Ponto.
        /// </summary>
        internal static string PrincipalOpcaoMarcarPonto {
            get {
                return ResourceManager.GetString("PrincipalOpcaoMarcarPonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar Ponto.
        /// </summary>
        internal static string RegistrarPonto {
            get {
                return ResourceManager.GetString("RegistrarPonto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique no botão abaixo para registrar o ponto.
        /// </summary>
        internal static string RegistrarPontoInfo {
            get {
                return ResourceManager.GetString("RegistrarPontoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to main_footer.
        /// </summary>
        internal static string StylesFooter {
            get {
                return ResourceManager.GetString("StylesFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        internal static string TextoBotaoGenericoFechar {
            get {
                return ResourceManager.GetString("TextoBotaoGenericoFechar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesso a Camera.
        /// </summary>
        internal static string TituloAcessoCamera {
            get {
                return ResourceManager.GetString("TituloAcessoCamera", resourceCulture);
            }
        }
    }
}
